name: momentum_app
description: Momentum

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  cloud_firestore: ^0.11.0+2
  html: ^0.13.3+3
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/graphics/
    - assets/fonts/
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 400